# Dockerfile
# Use the official Node.js image as a base image
FROM node:18-alpine

# Create and change to the app directory
WORKDIR /client

# Copy package.json and package-lock.json
COPY source/client/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY source/client .

# Build the Next.js app
RUN npm run build

# Expose the Next.js port
EXPOSE 3000

# Start the Next.js app
CMD ["npm", "run", "dev"]
